[pytest]
# Пусть pytest ищет тесты в папке tests и подхватывает src в PYTHONPATH
testpaths = tests
python_paths = src

# Регистрация кастомных меток
markers =
    integration: mark test as integration (runs with `-m integration`)
